### PR TITLE
feat: add otp flag for 2FA

### LINKED ISSUE #5: Support npm's 2FA (via OTP)
I ran into this when pushing shelljs v0.8. Now that NPM supports 2FA (and I've enabled it), we really need to find a way to support this in the script.

Current behavior is to do most things (bump the version, push the tags) but it fails during `npm publish`. First reaction might be to re-run the command, but this would re-bump the version and push a second tag (and would still fail).

I see a few solutions:

 1. Add a `--otp` flag. If present, then the otp value is forwarded to `npm publish`'s `--otp` flag. But if the user forgets to add this (I inevitably will forget), then we have the same issue where it's not safe to re-run the command.
 2. Always prompt the user for OTP, and pass this to `npm publish --otp=`. This isn't perfect, since the user may not have 2FA (yet we still prompt them). And if they pass the wrong thing, we need to remember to re-prompt them.
 3. Run `npm publish` in a way that it accepts user input. This doesn't work with `shell.exec()`, but does with `child_process.exec()`. Users are only prompted when they use 2FA. But if the user supplies a bad OTP, or hits ctrl-c, then the project is still in a bad state (git tags are pushed, but it isn't published).

Official docs for 2FA are [here](https://docs.npmjs.com/getting-started/using-two-factor-authentication).

### PR DESCRIPTION
**Pull request by nfischer**
This adds the `--otp` flag to support 2FA.

Fixes #5

### CODE REVIEW

**Review by freitagbr — COMMENTED** [review]
Is there a way to test this with actually  publishing to npm?

**Comment by nfischer** [comment]
Nope. I've been battle testing with the plugin releases I made. My plan is to do a final test for this by releasing the next shx. After that, I'll call this good as-is.

I tested a few failure cases when writing #6 (publish to repo I don't control, try to publish outside of project, try to publish when not signed into npm). With this PR, I also tested using a bad OTP. The script recovers fairly gracefully (everything is as-expected).

**Comment by nfischer** [comment]
@freitagbr ping (conflicts resolved)

**Comment by freitagbr** [comment]
Sorry, forgot about this. LGTM.

**Comment by nfischer** [comment]
Thanks!

**Comment by nfischer** [comment]
I'll test this in its final state one more time (releasing the next `shx`), and then I'll cut a new release for this.

**Pull request merged**
